apiVersion: apps/v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: myapp
spec:
  tolerations:
    - key: "prob"
      oprator: "Equal"
      value: "true"
      effect: "NoSchedule"
  containers:
    - name: mycontainer
      image: nginx:latest
      ports:
        - containerPort: 80
  nodeSelector:
    type: db